# Basic workflow

name: Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Import Secrets 
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }} 
          secrets: |
            secret/data/ci app_secret | TESTS ;

      - name: Step following 'Import Secrets'
        run: |
          echo '${{ toJson(steps.import-secrets.outputs) }}'
          echo "${{ toJson(steps.import-secrets.outputs) }}"
          echo "${{ toJson(steps.import-secrets.outputs) }}" > secrets.json
          cat secrets.json

      - name: Export JSON File
        run: |
          # Example: Move the file to another location or make it available for download
          mv secrets.json C:\HashiCorp

